services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes: 
      - mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influxdb/data:/var/lib/influxdb2
      - influxdb/config:/etc/influxdb2
    env_file:
      .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_DEFAULT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - mongodb/data:/data/db
    env_file:
      .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  hub:
    build: .
    ports:
      - "8000:5000"
    env_file:
      .env
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_DEFAULT_BUCKET=${INFLUX_DEFAULT_BUCKET}
    depends_on:
      - mosquitto
      - influxdb
      - mongodb

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
