// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	DeviceID    int32
	UserID      int32
	MacAddr     pgtype.Text
	DisplayName pgtype.Text
}

type ProvisionStaging struct {
	DeviceID int32
	Contract pgtype.Text
}

type Session struct {
	SessionID int32
	UserID    int32
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	UserID    int32
	Email     string
	Name      string
	PwHash    []byte
	CreatedAt pgtype.Timestamptz
	LastLogin pgtype.Timestamptz
}
